import ProductCard from "./ProductCard";
const ProductPage = () => {
    return (
        <div
            className="
            bg-light
            "
        >
            <div
                className="
                p-10
                grid lg:grid-cols-4 md:grid-cols-3 grid-cols-1 gap-[20px]
                max-w-[1200px] h-full m-auto 
                "
            >
                <ProductCard
                    name={"Jeans"}
                    price={"80$"}
                    image={"prdct4.png"}
                />
                <ProductCard
                    name={"Hoodie"}
                    price={"100$"}
                    image={"prdct1.png"}
                />
                <ProductCard
                    name={"Sweatshirt"}
                    price={"80$"}
                    image={"prdct2.png"}
                />
                <ProductCard
                    name={"Jacket"}
                    price={"140$"}
                    image={"prdct3.png"}
                />
                <ProductCard
                    name={"Jeans"}
                    price={"80$"}
                    image={"prdct4.png"}
                />
                <ProductCard
                    name={"Hoodie"}
                    price={"100$"}
                    image={"prdct1.png"}
                />
                <ProductCard
                    name={"Sweatshirt"}
                    price={"80$"}
                    image={"prdct2.png"}
                />
                <ProductCard
                    name={"Jacket"}
                    price={"140$"}
                    image={"prdct3.png"}
                />
                <ProductCard
                    name={"Jeans"}
                    price={"80$"}
                    image={"prdct4.png"}
                />
                <ProductCard
                    name={"Hoodie"}
                    price={"100$"}
                    image={"prdct1.png"}
                />
                <ProductCard
                    name={"Sweatshirt"}
                    price={"80$"}
                    image={"prdct2.png"}
                />
                <ProductCard
                    name={"Jacket"}
                    price={"140$"}
                    image={"prdct3.png"}
                />
                <ProductCard
                    name={"Jeans"}
                    price={"80$"}
                    image={"prdct4.png"}
                />
                <ProductCard
                    name={"Hoodie"}
                    price={"100$"}
                    image={"prdct1.png"}
                />
                <ProductCard
                    name={"Sweatshirt"}
                    price={"80$"}
                    image={"prdct2.png"}
                />
                <ProductCard
                    name={"Jacket"}
                    price={"140$"}
                    image={"prdct3.png"}
                />
            </div>
        </div>
    );
};

export default ProductPage;
